FROM centos:8

LABEL maintainer="dortiz@devops.faith"

RUN yum update -y && \
	yum install -y ca-certificates && \
	update-ca-trust force-enable && \
	rm -rf /var/lib/apt/lists/*

ADD krakend /usr/bin/krakend

RUN useradd -r -c "KrakenD user" -U krakend

USER krakend

VOLUME [ "/etc/krakend" ]

WORKDIR /etc/krakend

ENTRYPOINT [ "/usr/bin/krakend" ]
CMD [ "run", "-c", "/etc/krakend/krakend.json" ]

EXPOSE 8000 8090
